# .circleci/config.yml

version: 2.1

executors:
  linux-machine:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

jobs:
  build-and-push-images:
    # ... (This job remains the same) ...
    executor: linux-machine
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - run:
          name: Build and push backend image
          command: |
            docker build -t "$DOCKER_LOGIN/my-app-backend:${CIRCLE_SHA1}" -f backend/Dockerfile ./backend
            docker push "$DOCKER_LOGIN/my-app-backend:${CIRCLE_SHA1}"
      - run:
          name: Build and push frontend image
          command: |
            docker build -t "$DOCKER_LOGIN/my-app-frontend:${CIRCLE_SHA1}" -f frontend/Dockerfile ./frontend
            docker push "$DOCKER_LOGIN/my-app-frontend:${CIRCLE_SHA1}"

  deploy-and-verify:
    executor: linux-machine
    steps:
      - checkout
      - run:
          name: Install kubectl and Minikube
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo install minikube /usr/local/bin/
      - run:
          name: Start Minikube
          command: minikube start --driver=docker --kubernetes-version=v1.28.3
      - run:
          name: Update Kubernetes Manifests
          command: |
            sed -i "s/:LATEST_TAG/:${CIRCLE_SHA1}/g" k8s/*.yaml
            sed -i "s|bharatsurya1128|${DOCKER_LOGIN}|g" k8s/*.yaml
            echo "--- Updated Manifests ---"
            cat k8s/*.yaml
      - run:
          name: Deploy to Minikube
          command: kubectl apply -f k8s/
      - run:
          name: Verify Pod Readiness
          command: |
            echo "--- Waiting for pods to be ready... ---"
            
            sleep 300
            echo "--- Pods and Services ---"
            kubectl get pods,svc -o wide
      - run:
          name: Verify Webpage Access
          command: |
            # ✅ CORRECTED: Using 'frontend-service' from frontend-service.yaml
            FRONTEND_URL=$(minikube service frontend-service --url)
            
            echo "Accessing URL: $FRONTEND_URL"
            curl --fail --retry 5 --retry-delay 5 "$FRONTEND_URL"

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-images
      - deploy-and-verify:
          requires:
            - build-and-push-images