# backend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    # ✅ CORRECTED: Changed from 'backend' to 'my-app-backend'
    # This now correctly matches the label in backend-deployment.yaml
    app: my-app-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000