apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend # This is used by the Service
  template:
    metadata:
      labels:
        # ✅ This is the label you MUST match in your script.
        # Is it "app: backend" or something else?
        # For example, it might be this:
        app: my-app-backend 
        tier: backend
    spec:
      containers:
      - name: backend
        image: bharatsurya/my-app-backend