apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort # Exposes the service on each Node's IP at a static port
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007 # An accessible port for Minikube